import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import ReactPlayer from 'react-player';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<div>
					<div id='nav-wrapper'>
						{/* start main nav */}
						<nav id='main-nav'>
							<ul className='clearfix'>
								<li>
									{' '}
									<a href='#' className='sub-nav-toggle selected'>
										Demos
									</a>
									<ul className='sub-nav hidden'>
										<li>
											{' '}
											<a href='index.html' className='selected'>
												Agency
											</a>{' '}
										</li>
										<li>
											{' '}
											<a href='restaurant.html'>Restaurant</a>{' '}
										</li>
										<li>
											{' '}
											<a href='fitness.html'>Fitness</a>{' '}
										</li>
										<li>
											{' '}
											<a href='photography.html'>Photography</a>{' '}
										</li>
										<li>
											{' '}
											<a href='architect.html'>Architect</a>{' '}
										</li>
										<li>
											{' '}
											<a href='medical.html'>Medical</a>{' '}
										</li>
									</ul>
								</li>
								<li>
									{' '}
									<a href='portfolio.html'>Portfolio</a>
								</li>
								<li>
									{' '}
									<a href='about.html'>About</a>{' '}
								</li>
								<li>
									{' '}
									<a href='blog.html'>Blog</a>{' '}
								</li>
								<li>
									{' '}
									<a href='#' className='sub-nav-toggle'>
										Features
									</a>
									<ul className='sub-nav hidden'>
										<li>
											{' '}
											<a href='case-study-1.html'>Case Study 1</a>{' '}
										</li>
										<li>
											{' '}
											<a href='case-study-2.html'>Case Study 2</a>{' '}
										</li>
										<li>
											{' '}
											<a href='post-1.html'>Post</a>{' '}
										</li>
										<li>
											{' '}
											<a href='pricing.html'>Pricing</a>{' '}
										</li>
										<li>
											{' '}
											<a href='job-offers.html'>Job Offers</a>{' '}
										</li>
									</ul>
								</li>
								<li>
									{' '}
									<a href='contact.html'>Contact</a>{' '}
								</li>
							</ul>
						</nav>
						{/* end main nav */}
					</div>
					<div id='content-overlay' />
					<div id='wrap'>
						<div id='menu-button'>
							<div className='centralizer'>
								<div className='cursor'>
									<div id='nav-button'>
										{' '}
										<span className='nav-bar' /> <span className='nav-bar' />{' '}
										<span className='nav-bar' />{' '}
									</div>
								</div>
							</div>
						</div>
						{/* start header */}
						<header id='header' className='clearfix'>
							<h1 id='logo'>
								<a href='index.html'>Ilon Films</a>
							</h1>
							<ul className='social-list clearfix'>
								<li>
									{' '}
									<a href='#'>
										<i className='fa fa-behance' />
									</a>{' '}
								</li>
								<li>
									{' '}
									<a href='#'>
										<i className='fa fa-dribbble' />
									</a>{' '}
								</li>
								<li>
									{' '}
									<a href='#'>
										<i className='fa fa-xing' />
									</a>{' '}
								</li>
							</ul>
						</header>
						{/* end header */}
						{/* start content */}
						<div id='content'>
							<div
								className='full-width intro'
								style={{
									height: '100vh',
								}}>
								<div className='full-height not-completely-full'>
									<div className='fixed'>
										<video
											autoPlay
											muted
											loop
											className=' parallax parallax-banner'>
											<source src='./network-12716.mp4' type='video/mp4' />
										</video>
										{/* <video src={vedio}></video> */}
										{/* <figure className='background-image3 parallax parallax-banner' /> */}
									</div>
									<div className='full-height-wrapper white-text'>
										<div className='parent'>
											<div className='bottom'>
												<div className='container'>
													<div className='animatedblock delay2 animatedUp'>
														<div className='col-lg-6 col-md-offset-1 col-md-7'>
															<div className='banner-textblock'>
																<p className='large'> </p>
																<h1
																	className='header col-lg-11'
																	style={{ zIndex: '1000' }}>
																	Its all about illusion you create
																</h1>
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
										<div className='overlay' />
									</div>
								</div>
							</div>
							<section className='white'>
								<div className='container clearfix'>
									<div className='col-md-3 col-md-offset-1 col-sm-6'>
										<p className='large'>We specialize in:</p>
										<h4>Strategy &amp; Insights</h4>
										<h4>Digital</h4>
										<h4>Art Direction</h4>
										<div className='break' />
									</div>
									<div className='col-md-7 col-sm-6'>
										<p className='large'>
											Passionate Coders. Innovative Designers. Genius
											Storytellers.
										</p>
										<p className='large'>
											We are known for our unparalleled use of technology and
											deliver unsurpassed designs, that we, and our clients, are
											very proud of. Together we create award-winning brand
											experiences.{' '}
										</p>
										<p className='large'>
											Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf
											moon tempor, sunt aliqua put a bird on it squid
											single-origin coffee nulla assumenda shoreditch et.{' '}
										</p>
										<p>
											<a href='#' title className='arrow'>
												What We Do
											</a>
										</p>
									</div>
								</div>
							</section>
							<section>
								<div className='container clearfix'>
									<div className='col-lg-12 white-text centered extra-padding-bottom'>
										<h2 className='header'>Recent Work</h2>
									</div>
								</div>
								<div className='container clearfix'>
									<div
										id='container'
										style={{
											display: 'flex ',
											flexWrap: 'wrap',
											
										}}>
										<div className='element clearfix col-sm-6 home travel p-5'>
											<a
												href='case-study-2.html'
												data-title='Image Title'
												className='transition-link'>
												{' '}
												<ReactPlayer url='https://www.youtube.com/watch?v=ysz5S6PUM-U' />
												<div className='title-holder right'>
													<h3>Wireless AirPods</h3>
													<p className='large'>Apple</p>
												</div>
												<div className='overlay' />
											</a>{' '}
										</div>
										<div className='element clearfix col-sm-6 home travel p-5'>
											{' '}
											<a
												href='case-study-2.html'
												data-title='Image Title'
												className='transition-link'>
												{' '}
												<ReactPlayer url='https://www.youtube.com/watch?v=ysz5S6PUM-U' />
												<div className='title-holder right'>
													<h3>Wireless AirPods</h3>
													<p className='large'>Apple</p>
												</div>
												<div className='overlay' />
											</a>{' '}
										</div>
										<div className='element clearfix col-sm-6 home travel p-5'>
											{' '}
											<a
												href='case-study-1.html'
												data-title='Image Title'
												className='transition-link'>
												{' '}
												<ReactPlayer url='https://www.youtube.com/watch?v=ysz5S6PUM-U' />
												<div className='title-holder'>
													<h3>Just do it!</h3>
													<p className='large'>Nike</p>
												</div>
												<div className='overlay' />
											</a>{' '}
										</div>
										<div className='element clearfix col-sm-6 home travel p-5'>
											{' '}
											<a
												href='case-study-2.html'
												data-title='Image Title'
												className='transition-link'>
												{' '}
												<ReactPlayer url='https://www.youtube.com/watch?v=ysz5S6PUM-U' />
												<div className='title-holder right'>
													<h3>Wireless AirPods</h3>
													<p className='large'>Apple</p>
												</div>
												<div className='overlay' />
											</a>{' '}
										</div>
									</div>
								</div>
								<div className='container clearfix'>
									<div className='col-lg-12 white-text centered'>
										<p>
											<a href='portfolio.html' title className='arrow'>
												View All
											</a>
										</p>
									</div>
								</div>
							</section>
						</div>

						{/* end content */}
						<footer id='footer'>
							<div className='container clearfix'>
								<p className='alignleft'>© 2018, Belton Theme.</p>
								<p className='alignright'>
									Made with <i className='fa fa-heart' /> by{' '}
									<a
										href='http://www.weibergmedia.com'
										data-title='Premium HTML5 Website Templates'>
										weibergmedia
									</a>
									.
								</p>
							</div>
						</footer>
					</div>
					{/* end wrap */}
				</div>
			</main>
		</>
	);
}
